[rpc_endpoints]
buildbear = "https://rpc.buildbear.io/esquivelfabian"
[etherscan]
buildbear = { key = "0x6d1ac646f15a144a904e24afa4fd1d94d69983dd91b7835388de4d31eb40"  --40", url="https://rpc.buildbear.io/verify/etherscan/esquivelfabian" }
