[rpc_endpoints]
buildbear = "https://rpc.buildbear.io/esquivelfabian"
[etherscan]
buildbear = { key = "0x2491b230BaA58200B0C2857eaB1bFD523bE345b4", url="https://rpc.buildbear.io/verify/etherscan/esquivelfabian" }
